# Generated by Django 3.1.1 on 2021-03-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Summary',
            new_name='summary',
        ),
    ]
