# Generated by Django 3.1.1 on 2021-03-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210312_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tittle',
            field=models.CharField(default='jobtittle', max_length=10),
            preserve_default=False,
        ),
    ]
